# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lzp/ns-allinone-3.41/ns-3.41

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lzp/ns-allinone-3.41/ns-3.41

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(CMAKE_COMMAND) -E cmake_progress_start /home/lzp/ns-allinone-3.41/ns-3.41/CMakeFiles /home/lzp/ns-allinone-3.41/ns-3.41/scratch//CMakeFiles/progress.marks
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scratch/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lzp/ns-allinone-3.41/ns-3.41/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scratch/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scratch/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scratch/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(CMAKE_COMMAND) -P /home/lzp/ns-allinone-3.41/ns-3.41/CMakeFiles/VerifyGlobs.cmake
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
scratch/CMakeFiles/scratch_RoutingProtocol.dir/rule:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scratch/CMakeFiles/scratch_RoutingProtocol.dir/rule
.PHONY : scratch/CMakeFiles/scratch_RoutingProtocol.dir/rule

# Convenience name for target.
scratch_RoutingProtocol: scratch/CMakeFiles/scratch_RoutingProtocol.dir/rule
.PHONY : scratch_RoutingProtocol

# fast build rule for target.
scratch_RoutingProtocol/fast:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_RoutingProtocol.dir/build.make scratch/CMakeFiles/scratch_RoutingProtocol.dir/build
.PHONY : scratch_RoutingProtocol/fast

# Convenience name for target.
scratch/CMakeFiles/scratch_scratch-simulator.dir/rule:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scratch/CMakeFiles/scratch_scratch-simulator.dir/rule
.PHONY : scratch/CMakeFiles/scratch_scratch-simulator.dir/rule

# Convenience name for target.
scratch_scratch-simulator: scratch/CMakeFiles/scratch_scratch-simulator.dir/rule
.PHONY : scratch_scratch-simulator

# fast build rule for target.
scratch_scratch-simulator/fast:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_scratch-simulator.dir/build.make scratch/CMakeFiles/scratch_scratch-simulator.dir/build
.PHONY : scratch_scratch-simulator/fast

# Convenience name for target.
scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/rule:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/rule
.PHONY : scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/rule

# Convenience name for target.
scratch_subdir_scratch-subdir: scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/rule
.PHONY : scratch_subdir_scratch-subdir

# fast build rule for target.
scratch_subdir_scratch-subdir/fast:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/build.make scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/build
.PHONY : scratch_subdir_scratch-subdir/fast

RoutingProtocol.o: RoutingProtocol.cc.o
.PHONY : RoutingProtocol.o

# target to build an object file
RoutingProtocol.cc.o:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_RoutingProtocol.dir/build.make scratch/CMakeFiles/scratch_RoutingProtocol.dir/RoutingProtocol.cc.o
.PHONY : RoutingProtocol.cc.o

RoutingProtocol.i: RoutingProtocol.cc.i
.PHONY : RoutingProtocol.i

# target to preprocess a source file
RoutingProtocol.cc.i:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_RoutingProtocol.dir/build.make scratch/CMakeFiles/scratch_RoutingProtocol.dir/RoutingProtocol.cc.i
.PHONY : RoutingProtocol.cc.i

RoutingProtocol.s: RoutingProtocol.cc.s
.PHONY : RoutingProtocol.s

# target to generate assembly for a file
RoutingProtocol.cc.s:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_RoutingProtocol.dir/build.make scratch/CMakeFiles/scratch_RoutingProtocol.dir/RoutingProtocol.cc.s
.PHONY : RoutingProtocol.cc.s

scratch-simulator.o: scratch-simulator.cc.o
.PHONY : scratch-simulator.o

# target to build an object file
scratch-simulator.cc.o:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_scratch-simulator.dir/build.make scratch/CMakeFiles/scratch_scratch-simulator.dir/scratch-simulator.cc.o
.PHONY : scratch-simulator.cc.o

scratch-simulator.i: scratch-simulator.cc.i
.PHONY : scratch-simulator.i

# target to preprocess a source file
scratch-simulator.cc.i:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_scratch-simulator.dir/build.make scratch/CMakeFiles/scratch_scratch-simulator.dir/scratch-simulator.cc.i
.PHONY : scratch-simulator.cc.i

scratch-simulator.s: scratch-simulator.cc.s
.PHONY : scratch-simulator.s

# target to generate assembly for a file
scratch-simulator.cc.s:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_scratch-simulator.dir/build.make scratch/CMakeFiles/scratch_scratch-simulator.dir/scratch-simulator.cc.s
.PHONY : scratch-simulator.cc.s

subdir/scratch-subdir-additional-header.o: subdir/scratch-subdir-additional-header.cc.o
.PHONY : subdir/scratch-subdir-additional-header.o

# target to build an object file
subdir/scratch-subdir-additional-header.cc.o:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/build.make scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/subdir/scratch-subdir-additional-header.cc.o
.PHONY : subdir/scratch-subdir-additional-header.cc.o

subdir/scratch-subdir-additional-header.i: subdir/scratch-subdir-additional-header.cc.i
.PHONY : subdir/scratch-subdir-additional-header.i

# target to preprocess a source file
subdir/scratch-subdir-additional-header.cc.i:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/build.make scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/subdir/scratch-subdir-additional-header.cc.i
.PHONY : subdir/scratch-subdir-additional-header.cc.i

subdir/scratch-subdir-additional-header.s: subdir/scratch-subdir-additional-header.cc.s
.PHONY : subdir/scratch-subdir-additional-header.s

# target to generate assembly for a file
subdir/scratch-subdir-additional-header.cc.s:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/build.make scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/subdir/scratch-subdir-additional-header.cc.s
.PHONY : subdir/scratch-subdir-additional-header.cc.s

subdir/scratch-subdir.o: subdir/scratch-subdir.cc.o
.PHONY : subdir/scratch-subdir.o

# target to build an object file
subdir/scratch-subdir.cc.o:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/build.make scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/subdir/scratch-subdir.cc.o
.PHONY : subdir/scratch-subdir.cc.o

subdir/scratch-subdir.i: subdir/scratch-subdir.cc.i
.PHONY : subdir/scratch-subdir.i

# target to preprocess a source file
subdir/scratch-subdir.cc.i:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/build.make scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/subdir/scratch-subdir.cc.i
.PHONY : subdir/scratch-subdir.cc.i

subdir/scratch-subdir.s: subdir/scratch-subdir.cc.s
.PHONY : subdir/scratch-subdir.s

# target to generate assembly for a file
subdir/scratch-subdir.cc.s:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(MAKE) $(MAKESILENT) -f scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/build.make scratch/CMakeFiles/scratch_subdir_scratch-subdir.dir/subdir/scratch-subdir.cc.s
.PHONY : subdir/scratch-subdir.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... scratch_RoutingProtocol"
	@echo "... scratch_scratch-simulator"
	@echo "... scratch_subdir_scratch-subdir"
	@echo "... RoutingProtocol.o"
	@echo "... RoutingProtocol.i"
	@echo "... RoutingProtocol.s"
	@echo "... scratch-simulator.o"
	@echo "... scratch-simulator.i"
	@echo "... scratch-simulator.s"
	@echo "... subdir/scratch-subdir-additional-header.o"
	@echo "... subdir/scratch-subdir-additional-header.i"
	@echo "... subdir/scratch-subdir-additional-header.s"
	@echo "... subdir/scratch-subdir.o"
	@echo "... subdir/scratch-subdir.i"
	@echo "... subdir/scratch-subdir.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(CMAKE_COMMAND) -P /home/lzp/ns-allinone-3.41/ns-3.41/CMakeFiles/VerifyGlobs.cmake
	cd /home/lzp/ns-allinone-3.41/ns-3.41 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

